[package]
org = "ballerina"
name = "file"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../native/build/libs/file-native-@project.version@.jar"

[[platform.java11.dependency]]
path = "./lib/org.wso2.transport.local-file-system-@transport.version@.jar"


[[platform.java11.dependency]]
path = "../test-utils/build/libs/file-test-utils-@project.version@.jar"
scope = "testOnly"
