[package]
org = "ballerina"
name = "file"
version = "1.0.1"
authors = ["Ballerina"]
keywords = ["task", "job", "schedule"]
repository = "https://github.com/ballerina-platform/module-ballerina-task"
license = ["Apache-2.0"]
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/file-native-1.0.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/org.wso2.transport.local-file-system-6.0.55.jar"


[[platform.java11.dependency]]
path = "../test-utils/build/libs/file-test-utils-1.0.1-SNAPSHOT.jar"
scope = "testOnly"
