[plugin]
id = "file-compiler-plugin"
class = "io.ballerina.stdlib.file.compiler.FileCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/file-compiler-plugin-0.7.0-beta.3-SNAPSHOT.jar"
