[package]
org = "ballerina"
name = "file"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "io"
version = "@stdlib.io.version@"

[[dependency]]
org = "ballerina"
name = "time"
version = "@stdlib.time.version@"

[[dependency]]
org = "ballerina"
name = "log"
version = "@stdlib.log.version@"

[[dependency]]
org = "ballerina"
name = "os"
version = "@stdlib.os.version@"

[[dependency]]
org = "ballerina"
name = "regex"
version = "@stdlib.regex.version@"

[[platform.java11.dependency]]
path = "../file-native/build/libs/file-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "file"
version = "@project.version@"


[[platform.java11.dependency]]
path = "./lib/org.wso2.transport.local-file-system-6.0.55.jar"
groupId = "org.wso2.transport.file"
artifactId = "org.wso2.transport.local-file-system"
version = "6.0.55"


[[platform.java11.dependency]]
path = "../file-test-utils/build/libs/file-test-utils-@project.version@.jar"
groupId = "org.ballerinalang.stdlib.file"
scope = "testOnly"
artifactId = "file"
version = "@project.version@"
